namespace MonkeyFinder.Models;
// data: https://github.com/jamesmontemagno/app-monkeys/blob/master/MonkeysApp/monkeydata.json
// generated by: https://json2csharp.com/
public class Monkey
{
    public required string Name { get; set; }
    public required string Location { get; set; }
    public string? Details { get; set; }
    public string? Image { get; set; }
    public int Population { get; set; }
    public double Latitude { get; set; }
    public double Longitude { get; set; }
}
